version: "3.9"

services:

  client:
    image: mzserverdev
    command: tail -F anything
    volumes:
    - .:/home

  server:
    image: mzserverdev
    command: make run-server
    ports:
    - 8080:8080
    volumes:
    - .:/home